######################################################################
#
# File name : tb_mnist.udo
# Created on: Tue Oct 18 16:09:11 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
