######################################################################
#
# File name : tb_mnist_simulate.do
# Created on: Tue Oct 18 16:09:11 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_mnist xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_mnist_wave.do}

view wave
view structure
view signals

do {tb_mnist.udo}

run 1000ns
